name: CI/CD - Build, Push, and Update Manifests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 수동 실행 옵션 추가
    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      custom_tag:
        description: 'Custom image tag (optional)'
        required: false
        type: string
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Python 설정 및 테스트 실행
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      
      - name: Test with pytest
        run: |
          # 테스트 파일이 있는 경우만 실행
          if [ -d tests ]; then pytest tests; fi

      # 3. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. GitHub Container Registry 로그인
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 5. 컨테이너 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # 최상위 디렉토리에서 빌드
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/chabinhwang/snap-it-word2vec:latest
            ghcr.io/chabinhwang/snap-it-word2vec:${{ github.sha }}

      # 6. 매니페스트 업데이트 (이미지 태그 변경)
      - name: Checkout k8s manifests repository
        uses: actions/checkout@v3
        with:
          repository: chabinhwang/snap-it-word2vec-manifest
          token: ${{ secrets.MANIFEST_REPO_PAT }}
          path: k8s-manifests

      # 7. 이미지 태그만 업데이트
      - name: Update image tag in values.yaml
        run: |
          cd k8s-manifests
          sed -i "s|tag: .*|tag: ${{ github.sha }}|" values.yaml

      - name: Commit and push changes to manifest repo
        run: |
          cd k8s-manifests
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
